"""Tests for stage 4's constraint machinery and the accounting behind it.

Two real documents anchor most of these: the sR spec the loop plans from
(spec/sr.paper_only.json), and a hand-written host_knobs/host_storage pair
for the CBP2025 kit whose terms follow predictorsize() term by term
(fixtures/cbp2025.host_knobs.json). The second is checked against the kit
itself where the checkout is present, because a checker that only ever sees
hand-built documents tends to pass hand-built documents.
"""

import asyncio
import json
import re
import sys
from pathlib import Path

import pytest

import constants as C
import constraints as K
import dse
import helpers
import plan_checks
import plan_revision
import spec_checks

REPO = Path(__file__).resolve().parents[2]
FIXTURES = Path(__file__).resolve().parent / "fixtures"
KIT = REPO / "third_party" / "cbp2025"


@pytest.fixture
def spec():
    return json.loads((REPO / "spec" / "sr.paper_only.json").read_text())


@pytest.fixture
def host():
    doc = json.loads((FIXTURES / "cbp2025.host_knobs.json").read_text())
    return {"host_knobs": doc["host_knobs"], "host_storage": doc["host_storage"]}


def codes(findings):
    return sorted(f.code for f in findings)


# spec/sr.paper_only.json is regenerated by every distill run, and the
# distiller renames its knobs freely: `num_banks`, `NUM_BANKS`, `wt_num_banks`
# and `wt_banks` all name the same dimension across the runs in out/, and the
# count has ranged from four to fifteen. A test that pins a knob name or a
# storage total therefore goes red on the next run for a reason nobody should
# act on -- and a permanently red suite is how a real failure gets missed. So
# everything below derives what it needs from the spec in front of it.
#
# The host side is the opposite: fixtures/cbp2025.host_knobs.json is committed
# and hand-maintained, so its names and totals are safe to write down.
HOST_BASELINE_BITS = 524615


def feature_bits(spec):
    """What the spec's own formulas cost at their defaults."""
    feature, host = K.default_values(K.all_knobs(spec, None))
    total, _ = K.storage_bits(spec, None, feature, host)
    return total


def a_knob(spec, pred, why):
    """The first spec parameter matching `pred`.

    Skips rather than fails when this run's spec has no knob of the shape:
    the machinery is what is under test, and a spec that never grew one is
    not evidence the machinery broke.
    """
    for q in spec["parameters"]:
        if pred(q):
            return q, "SR_" + q["name"].upper()
    pytest.skip(f"the current spec declares no {why}")


def macro_cased(formula, spec):
    """A size_formula rewritten in the header's macro names."""
    for q in spec["parameters"]:
        formula = re.sub(rf"\b{re.escape(q['name'])}\b",
                         "SR_" + q["name"].upper(), formula)
    return formula


# ----------------------------------------------------------------- formulas


def test_formula_arithmetic():
    assert K.evaluate("2**logg * (a + 4)", {"logg": 10, "a": 12}) == 16384
    assert K.evaluate("1 << (b - 2)", {"b": 13}) == 2048
    assert K.evaluate("65 * (1 + max(t, d) + log2(n))", {"t": 14, "d": 12, "n": 256}) == 1495


def test_caret_is_refused_rather_than_read_as_xor():
    """2^10 is 8 in Python. A power written that way must be a finding,
    not a formula quietly off by a factor of 128."""
    with pytest.raises(K.FormulaError):
        K.evaluate("2^logg", {"logg": 10})


@pytest.mark.parametrize("expr", ["__import__('os')", "a.b", "a[0]", "a if a else 1", "a > 1"])
def test_formula_is_plain_arithmetic_only(expr):
    with pytest.raises(K.FormulaError):
        K.evaluate(expr, {"a": 1})


def test_names_in_excludes_functions():
    assert K.names_in("max(a, b) * log2(c)") == {"a", "b", "c"}


# ------------------------------------------------------------- spec formulas


def test_the_real_spec_is_accounted_and_clean(spec):
    """A canary on the checked-in spec, asserting what the loop guarantees
    rather than what one run happened to produce.

    The distill stage refuses to write this file with an `error` standing and
    promotes it with warnings standing, so `error` is the bar. The totals are
    checked against each other -- K.storage_bits re-derives from the formulas,
    resource_accounting states the sum -- which is the invariant that holds
    whatever the next run names its knobs.
    """
    errors = [f for f in spec_checks.run_checks(spec) if f.severity == "error"]
    assert errors == [], "\n".join(f"{f.pointer}: {f.message}" for f in errors)
    feature, host = K.default_values(K.all_knobs(spec, None))
    total, breakdown = K.storage_bits(spec, None, feature, host)
    assert total == spec["resource_accounting"]["total_storage_bits"]
    assert len(breakdown) == len(spec["state"])


def test_a_formula_that_disagrees_with_its_size_is_an_error(spec):
    """Double a formula the spec already wrote, so every name in it is one
    the spec declares. Writing knob names here pinned the test to whatever
    the last distill run happened to call them, and it then reported
    `formula_unknown_name` -- a different defect -- instead of failing."""
    entry = next((e for e in spec["state"] if e.get("size_formula")), None)
    if entry is None:
        pytest.skip("this spec states no size_formula")   # the field is optional
    entry["size_formula"] = f"2 * ({entry['size_formula']})"
    assert "formula_disagrees" in codes(spec_checks.run_checks(spec))


def test_a_formula_reading_an_undeclared_name_is_an_error(spec):
    spec["state"][1]["size_formula"] = "65 * 3 * ut_entries * counter_bits"
    assert "formula_unknown_name" in codes(spec_checks.run_checks(spec))


def test_a_storage_parameter_no_formula_reads_is_flagged(spec):
    """README's gap: nothing checked that the search could move the storage.

    Which parameters size a structure changes with every distill run, so the
    expectation is read off the formulas the spec states before they are
    stripped, not pinned to `/parameters/0` and `/parameters/4`.
    """
    sized = " ".join(str(s.get("size_formula", "")) for s in spec["state"])
    expected = {f"/parameters/{i}" for i, q in enumerate(spec["parameters"])
                if re.search(rf"\b{re.escape(q['name'])}\b", sized)}
    if not expected:
        pytest.skip("this spec states no size_formula naming a knob")
    for s in spec["state"]:
        s.pop("size_formula", None)
    found = [f for f in spec_checks.run_checks(spec)
             if f.code == "storage_param_unaccounted"]
    assert {f.pointer for f in found} >= expected
    assert all(f.severity == "warn" for f in found)


# ------------------------------------------------- the feature's own budget


def test_the_feature_budget_comes_off_the_persisted_plan():
    """Track minus what the host already spends, by the host's own
    accounting. `host_storage.baseline_bits` is `measure_host_storage`'s
    figure, which stage 2 will not accept a plan without, and it is the
    number stage 4 costs every candidate against."""
    plan, _tests, _rev = plan_revision.latest("cbp2025", C.FEATURE_NAME)
    assert plan["host_storage"]["baseline_bits"] == HOST_BASELINE_BITS
    assert (helpers.feature_budget_bits("iso-192KiB")
            == C.BUDGET_TRACKS_BITS["iso-192KiB"] - HOST_BASELINE_BITS)


def test_resolving_the_feature_budget_needs_no_cluster(monkeypatch):
    """The regression this exists for. The first version measured the host
    live, through a `ChiaFunction` reserving `cbp2025_host` -- so stage 1,
    which in paper_only mode holds no tools and needs no worker, asked the
    autoscaler for a host node and hung on "No available node types can
    fulfill resource request {'cbp2025_host': 1.0}".

    Poisoning the adapter rather than asserting it is unimportable. The
    first version of this test relied on the suite running where `ray` is
    absent, which made it a statement about the environment: it passed on a
    bare checkout and failed inside chia_env, where the import succeeds.
    An assertion that only holds on some machines is not a regression test.
    """
    class Poisoned:
        def __getattr__(self, name):
            raise AssertionError(
                f"resolving the feature budget reached the host adapter "
                f"({name}). Measuring live reserves cbp2025_host, which "
                f"stage 1 has no reason to hold and no way to get.")

    monkeypatch.setitem(sys.modules, "hosts.cbp2025.adapter", Poisoned())
    assert helpers.feature_budget_bits("iso-192KiB") is not None


def test_no_plan_for_a_host_leaves_the_budget_unset():
    """A first run has no plan, so there is nothing measured to compare
    against and the check stays on its prose fallback at `warn`."""
    assert helpers.feature_budget_bits("iso-192KiB", "champsim") is None
    assert helpers.feature_budget_bits("iso-9KiB") is None


def test_an_explicit_feature_budget_overrides_the_plan(monkeypatch):
    monkeypatch.setattr(C, "FEATURE_BUDGET_BITS", 4096)
    assert helpers.feature_budget_bits("iso-192KiB") == 4096


# ------------------------------------------------------------- host storage


def test_the_host_terms_reproduce_predictorsize(host):
    values = {k["name"]: k["default"] for k in host["host_knobs"]}
    assert sum(K.host_storage(host, values).values()) == 524615


def test_host_checks_pass_on_a_correct_pair(host):
    findings = plan_checks._check_host_knobs(host) + plan_checks._check_host_storage(host, 524615)
    assert [f for f in findings if f.severity == "error"] == []


@pytest.mark.skipif(not (KIT / "cbp2016_tage_sc_l.h").exists(), reason="no CBP2025 checkout")
def test_every_observed_line_is_in_the_real_kit(host):
    assert plan_checks._check_host_knobs(host, KIT) == []


def test_a_default_the_observed_line_does_not_hold_is_an_error(host):
    host["host_knobs"][0]["default"] = 9
    assert "host_default_not_observed" in codes(plan_checks._check_host_knobs(host))


@pytest.mark.skipif(not (KIT / "cbp2016_tage_sc_l.h").exists(), reason="no CBP2025 checkout")
def test_an_invented_observed_line_is_an_error(host):
    # A line cut short of its comment is still a quote; this one is not.
    host["host_knobs"][0]["observed"] = "#define LOGG 10  // log2 entries per tagged bank"
    assert "host_observed_missing" in codes(plan_checks._check_host_knobs(host, KIT))


def test_a_misnamed_host_macro_is_an_error(host):
    host["host_knobs"][0]["macro"] = "SR_LOGG"
    assert "host_macro_mismatch" in codes(plan_checks._check_host_knobs(host))


def test_terms_that_miss_the_measurement_are_an_error(host):
    host["host_storage"]["terms"] = host["host_storage"]["terms"][:-1]
    assert "host_storage_disagrees" in codes(plan_checks._check_host_storage(host))


def test_a_baseline_the_host_did_not_measure_is_an_error(host):
    assert "host_storage_unmeasured" in codes(plan_checks._check_host_storage(host, 523367))


def test_host_knobs_without_host_storage_is_an_error(host):
    del host["host_storage"]
    assert "host_storage_missing" in codes(plan_checks._check_host_storage(host))


def test_a_host_knob_no_term_reads_is_flagged(host):
    host["host_knobs"].append({**host["host_knobs"][0], "name": "logl", "macro": "HOST_LOGL",
                               "host_symbol": "LOGL", "observed": "#define LOGL 5",
                               "default": 5, "range": "[3, 7]"})
    found = [f for f in plan_checks._check_host_storage(host) if f.code == "host_knob_unaccounted"]
    assert [f.severity for f in found] == ["warn"]


def test_no_host_knobs_is_a_warning_not_an_error():
    found = plan_checks._check_host_knobs({"host_knobs": []})
    assert [(f.code, f.severity) for f in found] == [("no_host_knobs", "warn")]


# ----------------------------------------------------------------- revision


def test_a_revision_may_correct_a_host_knobs_range_but_not_its_default(host):
    new = json.loads(json.dumps(host))
    new["host_knobs"][0]["range"] = "[8, 12]"
    assert plan_revision._check_collection(
        "/plan", host, new, "host_knobs", *plan_revision._PORT_COLLECTIONS["host_knobs"]) == []
    new["host_knobs"][0]["default"] = 9
    assert "revision_froze_field" in codes(plan_revision._check_collection(
        "/plan", host, new, "host_knobs", *plan_revision._PORT_COLLECTIONS["host_knobs"]))


def test_a_revision_may_not_restate_the_measured_host_storage(host):
    new = json.loads(json.dumps(host))
    new["host_storage"]["baseline_bits"] = 500000
    assert "revision_froze_field" in codes(plan_revision._check_host_storage(host, new))


# ------------------------------------------------------------------- header


def test_the_header_carries_both_kinds_of_knob_and_the_cost_model(spec, host):
    cs = [K.storage_constraint("iso-64KiB", 524288)]
    header = dse.params_header(spec, host, constraint_set=cs)
    defines = [l for l in header.splitlines() if l.startswith("#define")]
    assert len(defines) == len(spec["parameters"]) + len(host["host_knobs"])
    assert "#define HOST_LOGG 10  // range: [7, 12]; sets LOGG" in header
    assert "// constraint: storage_bits <= 524288 (iso-64KiB)" in header
    # The cost model is written in the header's own names: every formula the
    # spec states, with its knobs macro-cased, appears verbatim.
    formulas = [e["size_formula"] for e in spec["state"] if e.get("size_formula")]
    if not formulas:
        pytest.skip("this spec states no size_formula to cost")
    for f in formulas:
        assert macro_cased(f, spec) in header
    assert "HOST_NBANKHIGH * 2 ** HOST_LOGG" in header


def test_the_default_header_is_a_legal_candidate(spec, host):
    """Stage 3 is told to create exactly this file, so it must parse back."""
    report = K.check_static(dse.params_header(spec, host), spec, host, [])
    assert report.errors == []
    assert report.host["logg"] == 10
    # Every knob the spec declares parses back, at its declared default.
    # `enum` knobs are the exception: the header renders them as an ordinal,
    # so the value that comes back is an int where the spec wrote a name.
    defaults = {q["name"]: q["default"] for q in spec["parameters"]}
    assert set(report.feature) == set(defaults)
    assert ({k: v for k, v in report.feature.items()
             if not isinstance(defaults[k], str)}
            == {k: v for k, v in defaults.items() if not isinstance(v, str)})


def test_defaults_do_not_fit_64kib_and_the_breakdown_says_why(spec, host):
    cs = [K.storage_constraint("iso-64KiB", 524288)]
    report = K.check_static(dse.params_header(spec, host, constraint_set=cs), spec, host, cs)
    assert not report.ok
    assert report.metrics["storage_bits"] == feature_bits(spec) + HOST_BASELINE_BITS
    assert "host:tagged tables, high banks" in report.breakdown
    assert "breaks storage_bits <= 524288" in report.message()


def test_shrinking_the_host_makes_room(spec, host):
    """How many banks the host must give back depends on how big the feature
    is, and that changes with every distill run -- the sR spec has ranged
    from 53863 to 92775 bits across the runs in out/. Solve for the shrink
    rather than pin it; what is under test is that one exists and that the
    accounting moves with it."""
    cs = [K.storage_constraint("iso-64KiB", 524288)]
    assert not K.check_static(
        dse.params_header(spec, host, constraint_set=cs), spec, host, cs).ok

    for nbh in range(20, -1, -1):
        header = dse.params_header(spec, host, host_overrides={"nbankhigh": nbh},
                                   constraint_set=cs)
        report = K.check_static(header, spec, host, cs)
        if report.ok:
            break
    else:
        pytest.fail("no legal nbankhigh: the host cannot pay for this feature")

    assert report.metrics["storage_bits"] <= 524288
    # Every bank given back is worth the same, so the total is the baseline
    # less a whole number of them.
    freed = feature_bits(spec) + HOST_BASELINE_BITS - report.metrics["storage_bits"]
    assert nbh == 20 or freed % (20 - nbh) == 0


def _refused(spec, host, edit):
    report = K.check_static(
        dse.params_header(spec, host).replace(*edit), spec, host, [])
    assert not report.ok
    return report.errors


def test_a_feature_knob_outside_its_range_is_refused(spec, host):
    q, macro = a_knob(spec, lambda x: isinstance(x.get("default"), int)
                      and not isinstance(x.get("default"), bool), "int knob")
    errs = _refused(spec, host,
                    (f"#define {macro} {q['default']}", f"#define {macro} 999999999"))
    assert any("outside" in e for e in errs)


def test_a_feature_knob_off_the_power_of_two_grid_is_refused(spec, host):
    q, macro = a_knob(spec, lambda x: "pow2" in str(x.get("range", ""))
                      and isinstance(x.get("default"), int), "pow2 knob")
    errs = _refused(spec, host,
                    (f"#define {macro} {q['default']}", f"#define {macro} {q['default'] + 1}"))
    assert any("power of two" in e for e in errs)


@pytest.mark.parametrize("edit,problem", [
    (("#define HOST_LOGG 10", "#define HOST_LOGG (1+9)"), "plain literal"),
    (("#define HOST_LOGG 10", "#define HOST_LOGGG 10"), "missing"),
])
def test_an_illegal_host_candidate_is_refused_with_a_reason(spec, host, edit, problem):
    assert any(problem in e for e in _refused(spec, host, edit))


def test_the_worked_toy_pair_renders_a_legal_header():
    """The toy spec spells its bool enable knob as 0; C accepts that, so must we."""
    spec = json.loads((FIXTURES / "tinysc.spec.json").read_text())
    plan = json.loads((FIXTURES / "tinysc.toy.plan.json").read_text())
    report = K.check_static(dse.params_header(spec, plan), spec, plan, [])
    assert report.errors == []
    assert report.host == {"bimodal_entries": 1024}


def test_a_measured_constraint_needs_no_new_code():
    cs = [K.Constraint("ipc_50perc_amean", ">=", 2.9, "ipc floor")]
    assert cs[0].phase == "measured"
    assert K.check_measured({"ipc_50perc_amean": 3.1}, cs) == []
    assert K.check_measured({"ipc_50perc_amean": 2.5}, cs) != []


# ---------------------------------------------------------------- preflight


def _fake_build(inert: set):
    """A build that ignores the macros in `inert`, the way a port that never
    wired them would: their value does not reach the binary."""
    def build(header):
        values, _ = K.parse_header(header)
        return json.dumps({m: v for m, v in values.items() if m not in inert},
                          sort_keys=True).encode()
    return build


def test_preflight_passes_when_every_knob_reaches_the_build(spec, host):
    report = dse.preflight(_fake_build(set()), spec, host, dse.params_header(spec, host))
    assert report["reproducible"] and report["blocking"] == []
    assert {k["result"] for k in report["knobs"]} <= {"live", "pinned"}
    assert "live" in {k["result"] for k in report["knobs"]}


def pin_a_knob(spec):
    """Give one of this spec's integer knobs a degenerate range.

    Constructed, not found. Whether a distill run declares a structurally
    fixed knob changes from run to run -- run 7 wrote
    `num_logical_registers [65, 65]` and `num_banks [8, 8]`, run 8 wrote
    `[32, 256]` and `[1, 16]` for the same two -- so a test that needs one
    to already exist goes red on the next run for a reason nobody should
    act on. The header above says this; these two tests learned it.
    """
    q = next((p for p in spec["parameters"]
              if p.get("type") == "int" and isinstance(p.get("default"), int)
              and not isinstance(p.get("default"), bool)), None)
    if q is None:
        pytest.skip("this spec declares no integer knob")
    q["range"] = f"[{q['default']}, {q['default']}]"
    return q


def test_a_pinned_knob_is_a_result_not_a_warning(spec, host):
    """A degenerate range has no second value to build, but it is a
    declaration rather than a defect -- sR's register file really is 65
    entries and its figure really does draw eight banks. Failing the whole
    preflight on one turned the suite red the moment run 7 declared its
    first."""
    q = pin_a_knob(spec)
    report = dse.preflight(_fake_build(set()), spec, host, dse.params_header(spec, host))
    entry = next(k for k in report["knobs"]
                 if k["macro"] == "SR_" + q["name"].upper())
    assert entry["result"] == "pinned"
    assert not any("no second legal value" in w for w in report["warnings"])


def test_a_knob_with_no_second_value_and_no_pin_still_warns():
    """The other reasons `alternate_value` gives up -- an unparsable range,
    a non-numeric default -- are knobs the DSE cannot search and nobody
    declared so. Widening `pinned` must not swallow them."""
    pinned = K.Knob("SR_A", "a", "int", 65, "[65, 65]", "feature")
    unparsable = K.Knob("SR_B", "b", "int", 4, "four to eight", "feature")
    one_choice = K.Knob("SR_C", "c", "enum", 0, "choices: only", "feature")
    two_choice = K.Knob("SR_D", "d", "enum", 0, "choices: a|b", "feature")
    assert K.is_pinned(pinned) and K.is_pinned(one_choice)
    assert not K.is_pinned(unparsable) and not K.is_pinned(two_choice)
    assert K.alternate_value(pinned) is None
    assert K.alternate_value(unparsable) is None


def test_a_bool_is_never_pinned():
    """A flag always has a second value, whatever its range string says."""
    assert not K.is_pinned(K.Knob("SR_F", "f", "bool", True, "", "feature"))


def test_a_pinned_default_must_be_the_value_the_range_pins(spec):
    """The other half of treating a pin as legitimate. No new check: with
    `lo == hi` the interval arm of `_check_parameters` already forces
    equality, and this pins that it does."""
    victim = pin_a_knob(spec)
    assert "param_range" not in codes(spec_checks._check_parameters(spec))
    victim["default"] = victim["default"] + 1
    assert "param_range" in codes(spec_checks._check_parameters(spec))


def test_an_inert_storage_knob_stops_the_search(spec, host):
    report = dse.preflight(_fake_build({"HOST_NBANKHIGH"}), spec, host,
                           dse.params_header(spec, host))
    assert len(report["blocking"]) == 1 and "HOST_NBANKHIGH" in report["blocking"][0]


def test_an_inert_knob_that_costs_nothing_is_only_a_warning(spec, host):
    """A knob no size_formula reads cannot move the storage total, so a port
    that never wired it is a warning rather than a stop. Which knob that is
    changes with every distill run, so find one instead of naming one."""
    sized = " ".join(str(e.get("size_formula", "")) for e in spec["state"])
    q, macro = a_knob(
        spec,
        lambda x: not re.search(rf"\b{re.escape(x['name'])}\b", sized),
        "knob outside every size_formula")
    report = dse.preflight(_fake_build({macro}), spec, host,
                           dse.params_header(spec, host))
    assert report["blocking"] == []
    assert any(macro in w for w in report["warnings"])


def test_unreproducible_builds_stop_the_preflight(spec, host):
    counter = iter(range(1000))
    report = dse.preflight(lambda h: str(next(counter)).encode(), spec, host,
                           dse.params_header(spec, host))
    assert not report["reproducible"] and report["blocking"]


@pytest.mark.parametrize("knob,expected", [
    (K.Knob("M", "n", "int", 512, "[128, 2048] pow2", "feature"), 256),
    (K.Knob("M", "n", "int", 128, "[128, 2048] pow2", "feature"), 256),
    (K.Knob("M", "n", "int", 6, "[3, 8]", "feature"), 5),
    (K.Knob("M", "n", "int", 3, "[3, 8]", "feature"), 4),
    (K.Knob("M", "n", "bool", True, "true|false", "feature"), False),
])
def test_alternate_value_prefers_the_smaller_legal_value(knob, expected):
    assert K.alternate_value(knob) == expected


# ---------------------------------------------------------------- evaluator


def test_evaluator_refuses_an_over_budget_candidate_without_building(spec, host, tmp_path):
    pytest.importorskip("skydiscover", reason="skydiscover/evolve-flows not installed")
    import sr_evaluator
    from skydiscover.evaluation.chia_evaluator import ChiaEvaluator

    cs = [K.storage_constraint("iso-64KiB", 524288)]
    ev = sr_evaluator.SRParamsEvaluator(
        "/nonexistent", ["int/x.gz"], str(tmp_path), 60, 60,
        spec=spec, port_plan=host, constraints=[c.as_dict() for c in cs])

    async def never(*a, **k):
        raise AssertionError("an over-budget candidate reached the build")

    try:
        ChiaEvaluator._dispatch_build, saved = never, ChiaEvaluator._dispatch_build
        over = asyncio.run(ev._dispatch_build(dse.params_header(spec, host), ""))
        closer = asyncio.run(ev._dispatch_build(
            dse.params_header(spec, host, host_overrides={"nbankhigh": 18}), ""))
    finally:
        ChiaEvaluator._dispatch_build = saved
        ev.close()
    assert over.artifacts["failure_stage"] == "constraints"
    assert over.metrics["storage_bits"] == 578478
    # Below every feasible score, and higher the closer it gets.
    assert 0 < over.metrics["combined_score"] < closer.metrics["combined_score"] < 1
